### ISSUE TITLE
Key binding

### ISSUE THREAD

**Issue by Jocky69** [Catalyst-Studios/MC-Evolution#9]
I have a bug with the key bindings. Every time i start the game, all the key binds are reset.
Version .0.2.3

**Comment by billbertking1** [comment]
If you navigate to `\Evolution\config\defaultoptions\` and open `options.txt`, does it have keybinds at the very bottom of the file?

**Comment by Jocky69** [comment]
the last line is 
modelPart_hat:true
[options.txt](https://github.com/user-attachments/files/17085564/options.txt)

**Comment by Jocky69** [comment]
There's one option.txt in the \Evolution folder whit key binds.

**Comment by billbertking1** [comment]
Delete the one with the keybinds, relaunch once or twice changing keybinds each time and see if that fixes it.

We're looking into other solutions to not use default options as well for next update

**Comment by Jocky69** [comment]
I delete twice the one with key binds in the \Evolution folder but it comes back every time. All the settings, key binds, graphics etc reset.

**Comment by billbertking1** [comment]
Recommend just disabling default options and that should fix it. Dev says it's not reproducible - https://github.com/TwelveIterationMods/DefaultOptions/issues/86

**Comment by Jocky69** [comment]
I checked other modpack and they don't have \Evolution\config\defaultoptions\ folder. The option.txt is on the \Evolution folder.

**Comment by Jocky69** [comment]
I've deleted the option.txt on the \Evolution\config but same thing.

**Comment by Jocky69** [comment]
How to disable default options?

**Comment by billbertking1** [comment]
If you're using CurseForge, click the 3 stacked buttons near "Play" then click "Profile Options" and click "Enable Content Management"
Close the menu, search for "Default Options" and then click the slider button to the right. It should go from orange to black/grey. Then relaunch.

Do note however, that you'll have to disable content management for it to tell you that there's an update. Also, please don't click "Update All"

(These instructions are purely off memory, if anything is wrong I apologize - I can get screenshots when I get back to my PC)

**Comment by Jocky69** [comment]
I enabled content management. But can't find ''Default Options'' :(

**Comment by PatrioticCross** [comment]
You are looking for this. 
![image](https://github.com/user-attachments/assets/81a8cd72-a287-4d4b-9efc-c6d5f5c928d4)

**Comment by Jocky69** [comment]
Thanks
